# Generated by Django 5.1.7 on 2025-04-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_applicants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="applicants",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="jobs.application"
            ),
        ),
    ]
