# Generated by Django 4.2.20 on 2025-05-03 14:56

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0003_alter_job_applicants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationstatuslog",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "Application Status Log",
                "verbose_name_plural": "Application Status Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="jobindustry",
            options={
                "ordering": ["name"],
                "verbose_name": "Job Industry",
                "verbose_name_plural": "Job Industries",
            },
        ),
        migrations.AlterModelOptions(
            name="jobsubcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Job Subcategory",
                "verbose_name_plural": "Job Subcategories",
            },
        ),
        migrations.AlterModelOptions(
            name="savedjob",
            options={
                "ordering": ["-saved_at"],
                "verbose_name": "Saved Job",
                "verbose_name_plural": "Saved Jobs",
            },
        ),
        migrations.RemoveField(
            model_name="application",
            name="employer",
        ),
        migrations.RemoveField(
            model_name="job",
            name="applicants",
        ),
        migrations.AddField(
            model_name="applicationstatuslog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who initiated the status change",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedjob",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about why this job was saved",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="feedback",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_shown_up",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="application",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90.0")),
                    django.core.validators.MaxValueValidator(Decimal("90.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180.0")),
                    django.core.validators.MaxValueValidator(Decimal("180.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="manual_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Applied", "Applied"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                    ("Withdrawn", "Withdrawn"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationstatuslog",
            name="changed_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="applicationstatuslog",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Applied", "Applied"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                    ("Withdrawn", "Withdrawn"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationstatuslog",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Applied", "Applied"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                    ("Withdrawn", "Withdrawn"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="actual_shift_end",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="actual_shift_start",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="applicants_needed",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(
                default="No description provided",
                validators=[django.core.validators.MaxLengthValidator(5000)],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("single_day", "Single Day"),
                    ("multiple_days", "Multiple Days"),
                    ("temporary", "Temporary"),
                    ("part_time", "Part Time"),
                    ("full_time", "Full Time"),
                ],
                db_index=True,
                default="single_day",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("held", "Held in Escrow"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="recurring_days",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated days (e.g., Monday,Wednesday,Friday)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters and commas allowed", regex="^[a-zA-Z, ]+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="service_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                    ("night", "Night"),
                    ("day", "Day"),
                    ("flexible", "Flexible"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="jobindustry",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Industry name must be at least 2 characters"
                    ),
                    django.core.validators.MaxLengthValidator(255),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jobindustry",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="jobsubcategory",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(255),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jobsubcategory",
            name="saved_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="savedjob",
            name="saved_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["is_shown_up"], name="jobs_applic_is_show_2e620d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job", "applicant", "status"],
                name="jobs_applic_job_id_f55c51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationstatuslog",
            index=models.Index(
                fields=["application", "changed_at"],
                name="jobs_applic_applica_8da6cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationstatuslog",
            index=models.Index(
                fields=["new_status", "changed_at"],
                name="jobs_applic_new_sta_e1f39c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active"], name="jobs_job_is_acti_b6ae73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "shift_type"], name="jobs_job_job_typ_54c10e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobindustry",
            index=models.Index(fields=["name"], name="jobs_jobind_name_fab9c5_idx"),
        ),
        migrations.AddIndex(
            model_name="jobsubcategory",
            index=models.Index(
                fields=["industry", "name"], name="jobs_jobsub_industr_17094b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobsubcategory",
            index=models.Index(fields=["name"], name="jobs_jobsub_name_82de4f_idx"),
        ),
        migrations.AddIndex(
            model_name="savedjob",
            index=models.Index(
                fields=["user", "saved_at"], name="jobs_savedj_user_id_50c67d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedjob",
            index=models.Index(
                fields=["job", "saved_at"], name="jobs_savedj_job_id_c8c51e_idx"
            ),
        ),
    ]
