# Generated by Django 5.2 on 2025-05-08 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_alter_applicationstatuslog_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationStatusLog",
        ),
    ]
