# Generated by Django 4.2.11 on 2025-06-01 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0005_delete_applicationstatuslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Applied", "Applied"),
                            ("Rejected", "Rejected"),
                            ("Accepted", "Accepted"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Applied", "Applied"),
                            ("Rejected", "Rejected"),
                            ("Accepted", "Accepted"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="jobs.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the status change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Status Log",
                "verbose_name_plural": "Application Status Logs",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "changed_at"],
                        name="jobs_applic_applica_8da6cd_idx",
                    ),
                    models.Index(
                        fields=["new_status", "changed_at"],
                        name="jobs_applic_new_sta_e1f39c_idx",
                    ),
                ],
            },
        ),
    ]
