# Generated by Django 4.2.11 on 2025-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_alter_application_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Applied", "Applied"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                    ("Withdrawn", "Withdrawn"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationstatuslog",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Applied", "Applied"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                    ("Withdrawn", "Withdrawn"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationstatuslog",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Applied", "Applied"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                    ("Withdrawn", "Withdrawn"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
