# Generated by Django 5.2.3 on 2025-08-06 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobindustry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Industry name must be at least 2 characters'), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='jobsubcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
