# Generated by Django 4.2.16 on 2025-10-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_end_time_alter_job_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Ongoing', 'Ongoing'), ('Withdrawn', 'Withdrawn')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='new_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Ongoing', 'Ongoing'), ('Withdrawn', 'Withdrawn')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='old_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Ongoing', 'Ongoing'), ('Withdrawn', 'Withdrawn')], db_index=True, max_length=20),
        ),
    ]
