# Generated by Django 4.2.16 on 2026-02-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_rename_date_to_start_and_add_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_date_3ae85a_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['start_date', 'start_time'], name='jobs_job_start_d_e4e417_idx'),
        ),
    ]
