# Generated by Django 4.2.20 on 2025-05-04 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_alter_applicationstatuslog_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("disputes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="jobs.application",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_review", "In Review"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("escalated", "Escalated"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
