# Generated by Django 5.2 on 2025-05-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_dispute_application_dispute_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], db_index=True, default='open', max_length=20),
        ),
    ]
