# Generated by Django 4.2.20 on 2025-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("paystack", "Paystack"), ("flutterwave", "Flutterwave")],
                max_length=20,
                null=True,
            ),
        ),
    ]
