# Generated by Django 4.2.20 on 2025-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_payment_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_status",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="confirmed_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="refund_requested",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("paystack", "Paystack"), ("flutterwave", "Flutterwave")],
                max_length=20,
                null=True,
            ),
        ),
    ]
