# Generated by Django 4.2.20 on 2025-05-04 11:51

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_rename_payment_status_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="service_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.10"), max_digits=10
            ),
        ),
    ]
