# Generated by Django 5.2 on 2025-05-20 10:46

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Refunded", "Refunded"),
                    ("Failed", "Failed"),
                    ("Paid", "Paid"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
