# Generated by Django 5.2 on 2025-05-21 16:31

import django_fsm
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="service_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                    ("paid", "Paid"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
