# Generated by Django 4.2.11 on 2025-05-30 13:27

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=django_fsm.FSMField(default="pending", max_length=50),
        ),
    ]
