# Generated by Django 4.2.11 on 2025-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0010_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
