# Generated by Django 5.2.3 on 2025-08-06 14:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_payment_payment_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='job',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='paystack_reference',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='job',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='payment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payment.payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='release_conditions',
            field=models.TextField(blank=True, help_text='Conditions that must be met to release escrow'),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='flutterwave_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='escrow_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('wallet', 'Wallet'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_fsm.FSMField(choices=[('success', 'Success'), ('successful', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('pending', 'Pending'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
