# Generated by Django 4.2.16 on 2025-09-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_end_time_alter_job_start_time_and_more'),
        ('payment', '0013_alter_wallet_options_remove_escrowpayment_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
    ]
