# Generated by Django 4.2.16 on 2025-10-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_payment_job'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_id'], name='payment_pay_payer_i_97dc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recipient_id'], name='payment_pay_recipie_8a5de9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['job_id'], name='payment_pay_job_id_cd73ea_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_pay_created_671024_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_pay_status_19fbf4_idx'),
        ),
    ]
