branch-defaults:
  backend:
    environment: payshift-production
    group_suffix: null
  main:
    environment: payshift-production
    group_suffix: null
environment-defaults:
  payshift-production:
    branch: null
    repository: null
environment_default: payshift-production
global:
  application_name: paeshift
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: new-account
  repository: null
  sc: git
  workspace_type: Application
