# Generated by Django 4.2.20 on 2025-05-04 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0002_achievement_badge_clientachievement_leaderboard_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="clientachievement",
            name="achievement",
        ),
        migrations.DeleteModel(
            name="Leaderboard",
        ),
        migrations.RemoveField(
            model_name="levelconfig",
            name="badge_reward",
        ),
        migrations.RemoveField(
            model_name="nigeriaachievement",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="socialshare",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="socialshare",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="socialshare",
            name="user",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.RemoveField(
            model_name="teamachievement",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="teamachievement",
            name="team",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userpoints",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userreward",
            name="reward",
        ),
        migrations.RemoveField(
            model_name="userreward",
            name="user",
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.DeleteModel(
            name="ClientAchievement",
        ),
        migrations.DeleteModel(
            name="LevelConfig",
        ),
        migrations.DeleteModel(
            name="NigeriaAchievement",
        ),
        migrations.DeleteModel(
            name="RewardItem",
        ),
        migrations.DeleteModel(
            name="SocialShare",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="TeamAchievement",
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
        migrations.DeleteModel(
            name="UserPoints",
        ),
        migrations.DeleteModel(
            name="UserReward",
        ),
    ]
