# Generated by Django 5.2 on 2025-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0003_remove_achievement_badge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
