# Generated by Django 5.2 on 2025-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0004_review_review_review_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
