# Generated by Django 4.2.11 on 2025-05-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_delete_applicationstatuslog"),
        ("rating", "0005_review_is_read"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_rating_per_user",
        ),
        migrations.AddField(
            model_name="review",
            name="job",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="jobs.job",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("reviewer", "reviewed", "job"),
                name="unique_rating_per_user_per_job",
            ),
        ),
    ]
