# Generated by Django 4.2.11 on 2025-06-10 06:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0008_alter_application_status_and_more"),
        ("rating", "0006_remove_review_unique_rating_per_user_review_job_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("reviewer", "reviewed", "job")},
        ),
    ]
