# Generated by Django 4.2.16 on 2025-10-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewed_id'], name='rating_revi_reviewe_9c4d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer_id'], name='rating_revi_reviewe_5427ab_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['job_id'], name='rating_revi_job_id_8df7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='rating_revi_created_9f03da_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer_id', 'reviewed_id', 'job_id'], name='rating_revi_reviewe_cce5ea_idx'),
        ),
    ]
