# Generated by Django 4.2.11 on 2025-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_has_2fa_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
