# Generated by Django 4.2.11 on 2025-06-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                help_text="User's role in the system",
                max_length=50,
                verbose_name="role",
            ),
        ),
    ]
