# Generated by Django 4.2.11 on 2025-06-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_pic",
        ),
        migrations.CreateModel(
            name="ProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Uploaded profile picture",
                        upload_to="profile_pics/",
                        verbose_name="profile picture",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this the current profile picture?"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="Profile this picture belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile picture",
                "verbose_name_plural": "profile pictures",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
