# Generated by Django 4.2.16 on 2025-10-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_profile_pic_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_details',
            field=models.JSONField(blank=True, default=dict, help_text='Bank or account details', null=True),
        ),
    ]
