# Generated by Django 4.2.16 on 2025-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_account_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_details',
            field=models.JSONField(blank=True, default=dict, help_text="Stores user's bank account info (bank name, account number, etc.)", null=True, verbose_name='account details'),
        ),
    ]
