# Generated by Django 4.2.16 on 2025-10-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_account_details'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='accounts_cu_usernam_ab560e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='accounts_cu_is_acti_2885e2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user_id'], name='accounts_ot_user_id_55ce4b_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['is_verified'], name='accounts_ot_is_veri_3f7da9_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['created_at'], name='accounts_ot_created_3fc6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user_id', 'is_verified'], name='accounts_ot_user_id_c5d826_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user_id'], name='accounts_pr_user_id_97e401_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='accounts_pr_role_fae1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['joined_at'], name='accounts_pr_joined__5e830d_idx'),
        ),
    ]
