# Generated by Django 4.2.16 on 2026-02-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_accounts_cu_email_5ce40b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('login', 'Login')], default='registration', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.TextField(blank=True, help_text='JSON metadata for the OTP', null=True)),
            ],
            options={
                'verbose_name': 'Temporary OTP',
                'verbose_name_plural': 'Temporary OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_te_email_3e7ec4_idx'), models.Index(fields=['email', 'otp_type'], name='accounts_te_email_93a996_idx'), models.Index(fields=['is_verified'], name='accounts_te_is_veri_90cf8e_idx'), models.Index(fields=['created_at'], name='accounts_te_created_fbd5a5_idx')],
            },
        ),
    ]
