# Generated by Django 5.1.7 on 2025-04-30 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="JobTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Time"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Time"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracker",
                        to="jobs.job",
                        verbose_name="Associated Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Tracker",
                "verbose_name_plural": "Job Trackers",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="userlocatio_status_17f529_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="userlocatio_started_46bcce_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable location identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Latitude in decimal degrees (-90 to +90)",
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Longitude in decimal degrees (-180 to +180)",
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Full address from reverse geocoding",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last Updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Location",
                "verbose_name_plural": "User Locations",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_updated"],
                        name="userlocatio_user_id_788726_idx",
                    ),
                    models.Index(
                        fields=["address", "-last_updated"],
                        name="userlocatio_address_467597_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="userlocatio_latitud_2d500b_idx",
                    ),
                ],
                "unique_together": {("user",)},
            },
        ),
    ]
