# Generated by Django 5.2 on 2025-05-05 11:06

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlocation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationhistory',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Latitude in decimal degrees (-90 to +90)', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Longitude in decimal degrees (-180 to +180)', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['user', '-timestamp'], name='userlocatio_user_id_857de4_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['latitude', 'longitude'], name='userlocatio_latitud_5a39c0_idx'),
        ),
    ]
