# Generated by Django 4.2.20 on 2025-05-04 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view_profile", "View Profile"),
                            ("update_profile", "Update Profile"),
                            ("view_job", "View Job"),
                            ("create_job", "Create Job"),
                            ("apply_job", "Apply to Job"),
                            ("payment", "Payment"),
                            ("message", "Message"),
                            ("location_update", "Location Update"),
                            ("dispute", "Dispute Action"),
                            ("admin_action", "Admin Action"),
                            ("simulation", "Run Simulation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="godmode_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity Log",
                "verbose_name_plural": "User Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulation_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin Registration"),
                            ("client", "Client Registration"),
                            ("applicant", "Applicant Registration"),
                            ("job", "Job Creation"),
                            ("application", "Job Application"),
                            ("payment", "Payment Processing"),
                            ("dispute", "Dispute Management"),
                            ("location", "Location Streams"),
                            ("webhook", "Payment Webhook"),
                            ("full", "Full End-to-End Simulation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation Run",
                "verbose_name_plural": "Simulation Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimed_address", models.TextField()),
                ("claimed_latitude", models.FloatField(blank=True, null=True)),
                ("claimed_longitude", models.FloatField(blank=True, null=True)),
                ("actual_locations", models.JSONField(default=list)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("suspicious", "Suspicious"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Verification",
                "verbose_name_plural": "Location Verifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
