# Generated by Django 4.2.11 on 2025-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
