# Generated by Django 4.2.16 on 2025-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='navigate_url',
            field=models.CharField(blank=True, default='/', max_length=300, null=True),
        ),
    ]
